# -*- coding: utf-8 -*-
import scrapy
import requests
from scrapy import signals
from scrapy.xlib.pydispatch import dispatcher
import smtplib 
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders 

class RedmiSpider(scrapy.Spider):
    name = 'Redmi'
    allowed_domains = []
    start_urls = ['https://www.flipkart.com/search?q=Redmi&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off']

    def __init__(self):
        dispatcher.connect(self.spider_closed, signals.spider_closed)

    def spider_closed(self, spider):
        fromaddr = 'pycoders2432@gmail.com'
        toaddr = 'nitesh156200@gmail.com'
        msg = MIMEMultipart() 

        msg['From'] = fromaddr 

        msg['To'] = toaddr 

        msg['Subject'] = "Report generated by spider"

        body = "The items that has been scraped is sent in excel format"

        msg.attach(MIMEText(body, 'plain')) 

        filename = "/home/niteshkumar/Desktop/Scraping/RedmiMobiles/RedmiMobiles/spiders/mobile.csv"
        attachment = open("/home/niteshkumar/Desktop/Scraping/RedmiMobiles/RedmiMobiles/spiders/mobile.csv", "rb") 

        p = MIMEBase('application', 'octet-stream') 

        p.set_payload((attachment).read()) 

        encoders.encode_base64(p) 

        p.add_header('Content-Disposition', "attachment; filename= %s" % filename) 

        msg.attach(p) 

        s = smtplib.SMTP('smtp.gmail.com', 587) 

        s.starttls() 
            
        s.login(fromaddr, "pyotp2432") 

        text = msg.as_string()  
        s.sendmail(fromaddr, toaddr, text) 
            
        s.quit() 
    

    def parse(self, response):
        Page_URLs = response.xpath('..//a[contains(@class,"_2Xp0TH")]//@href').extract()
        for URL in Page_URLs:
            Actual_URL = 'https://www.flipkart.com' + URL
            yield scrapy.Request(Actual_URL,callback=self.parse_mobile)

    def parse_pagenation(self, response):
        Mobile_URLs = response.xpath('..//a[@class = "_31qSD5"]//@href').extract()
        for URL in Mobile_URLs:
            Actual_URL = 'https://www.flipkart.com' + URL
            yield scrapy.Request(Actual_URL,callback=self.parse_details)

    def parse_mobile(self, response):
        mobile_name = response.xpath('..//div[@class = "_3wU53n"]//text()').extract()
        price =  response.xpath('..//div[@class = "_1vC4OE _2rQ-NK"]//text()').extract()

        for a,b in zip(mobile_name,price):
            data =  {
                "Model Name" : a,
                "Price" : b
            }
            yield data

    def parse_details(self, response):
        specs_heading = response.xpath('..//td[@class="_3-wDH3 col col-3-12"]//text()').extract()
        specs_desc = response.xpath('..//li[@class="_3YhLQA"]//text()').extract()

        for a,b in zip(specs_heading,specs_desc):
            data = {
                "Title" : a,
                "Description" : b
            }
            yield data
